<!--footer 底部 start-->
<footer id="footer" class="z_footer">
    <nav>
        <a target="_top" href="<?=Url::createUrl('/game/index', array('from' => 'listpage')) ?>" title="久乐H5游戏首页">
            <i class="icons i_ft01"></i>
            <span>首页</span>
        </a>
        <a target="_top" href="/game/type.html?tc=手游" title="久乐H5游戏资讯">
            <i class="icons i_ft02"></i>
            <span>手游</span>
        </a>
        <a target="_top" href="/game/type.html?tc=h5" title="久乐H5游戏大厅、游戏中心">
            <i class="icons i_ft03"></i>
            <span>H5</span>
        </a>
        <a target="_top" href="/activity/giftbag.html" title="久乐H5游戏活动、礼包、兑换码">
            <i class="icons i_ft04"></i>
            <span>礼包</span>
        </a>
        <a target="_top" href="/user/index.html" title="我的久乐游戏">
            <i class="icons i_ft05"></i>
            <span>我的</span>
        </a>
    </nav>
</footer>
<link href="/css/app.css" rel="stylesheet" type="text/css">
<div id="weixin_an" style="display: none">
    <div class="click_opacity"></div>
    <div class="to_btn">
        <span class="span1"><img src="/public/channel/click_btn.png"></span>
        <span class="span2"><em>1</em> 点击右上角<img src="/public/channel/menu_android.png">打开菜单</span>
        <span class="span2 android_open"><em>2</em> 选择<img src="/public/channel/android.png"></span>
    </div>
</div>
<div class="qrcode_image" style="text-align: center">
    <span style="margin-bottom: 1px">按住CTRL+D键收藏本站</span>
    <div id="qrcode" style="margin-top: 1px;"></div>
    <span>扫码进入 《游戏中心》 手机版</span>
</div>
<!--二维码-->
<script src="/public/scripts/jquery-1.11.1.min.js"></script>
<script src="/public/scripts/jquery.qrcode.min.js"></script>

<!--<div class="qrcode_image">-->
<!--        <img src="/qrcode/game.html?addr=--><?//="http://".$_SERVER['HTTP_HOST'].$_SERVER['REQUEST_URI']?><!--">-->
<!--</div>-->
<?php
        //第一次缓存链接
        $addr="http://".$_SERVER['HTTP_HOST'].$_SERVER['REQUEST_URI'];
        $session=Yaf_Session::getInstance();
        if($session->has('url')){
	        $addr=$session->get('url');
        }else {
            $session->set('url',$addr);
        }
?>
<script>
    $('#qrcode').qrcode({
        text:"<?=$addr?>",
        width: 160, //宽度
        height:160, //高度
        background: "#ffffff",
        correctLevel: 0,//纠错等级
    });

    /**
     * 统计
     */
    function countDownload(obj,appid){
        // $.post("/index/game/countgame",{game_id:game_id},function(result){
        //     console.log(result);
        // });
        var ua = navigator.userAgent.toLowerCase();
        if (/iphone|ipad|ipod/.test(ua)) {
            if (appid == 100) {
                $(obj).attr('href', '#');
                alert('苹果手机不能下载安卓包哦！');
                return;
            }
        } else if (/android/.test(ua)) {
            if (appid == 101) {
                $(obj).attr('href', '#');
                alert('安卓手机不能下载苹果包哦！');
                return;
            }
        if (ua.match(/MicroMessenger/i) == "micromessenger") {
            $(obj).attr('href', '#');
            $('#weixin_an').show();
            }
        }
    }
</script>

