<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no"/>
    <title>客服中心</title>
    <link rel="stylesheet" href="/public/styles/base.css"/>
    <link rel="stylesheet" href="/styles/pay_edit.css"/>
    <link rel="stylesheet" href="/layui/css/layui.css"/>
    <style>
        a{color: #0b0b0b!important;text-decoration:underline}
        .layui-input-block {
             margin-left: 0!important;
            min-height: 36px;
        }
    </style>
</head>
<body style="background-color:#ffffff">
<!--div.container 总外框  start-->
<div>
        <table class="layui-table" lay-skin="line">

                <colgroup>
                    <col>
                    <col>
                    <col>
                </colgroup>
                <thead>
                <tr>
                    <th>标题</th>
                    <th>问题类型</th>
                    <th>状态</th>
                    <th>新回复</th>
                </tr>
                </thead>
                <tbody>
                <?php foreach ($list as $key=>$value):?>
                <tr <?php if($value['now_reply']=='是'):?>style="background-color: red"<?php endif;?>>
                    <td><?=$value['title']?></td>
                    <td><a href="/index/sdkapi/details?feed_id=<?=$value['feed_id']?>"><?=$value['type']?></a></td>
                    <td><?=$value['status']?></td>
                    <td ><?=$value['now_reply']?></td>
                </tr>
                <?php endforeach;?>
                </tbody>
        </table>
<!--    <div class="layui-form-item">-->
<!--        <div class="layui-input-block" style="text-align: center">-->
<!--            <a >我已提交的点击查看</a>-->
<!--        </div>-->
<!--    </div>-->
<!--    <div style="float: left">-->
<!--        <image src="/images/login/qq.png" width="20" height="20"></image><a onclick="jump_qq(this)" data-id="--><?//= $info['service_qq'] ?><!--" href="javascript:void(0);">客服:--><?//= $info['service_qq']; ?><!--</a>-->
<!--    </div>-->
<!--        <div style="float: right">-->
<!--            <image src="/images/login/qq.png" width="20" height="20"></image><a onclick="jump_qq(this)" data-id="--><?//= $info['service_qq2'] ?><!--" href="javascript:void(0);">玩家群:--><?//= $info['service_qq2']; ?><!--</a>-->
<!--        </div>-->
</div>
<!--div.container 总外框  end-->
<script src="/public/scripts/jquery-1.11.1.min.js"></script>
<script src="/public/scripts/jquery.mobile.min.js"></script>
<script src="/layui/layui.js"></script>
<script>
    layui.use(['layer', 'form'], function(){
        var layer = layui.layer
            ,form = layui.form;
    });
    function IsPC() {
        var userAgentInfo = navigator.userAgent;
        var Agents = ["Android", "iPhone",
            "SymbianOS", "Windows Phone",
            "iPad", "iPod"];
        var flag = true;
        for (var v = 0; v < Agents.length; v++) {
            if (userAgentInfo.indexOf(Agents[v]) > 0) {
                flag = false;
                break;
            }
        }
        return flag;
    }
    function jump_qq(obj) {
        var qq = $(obj).attr('data-id');
        if (IsPC()) {
            window.open("http://wpa.qq.com/msgrd?v=3&uin=" + qq + "&site=qq&menu=yes");
        } else {
            window.open("mqqwpa://im/chat?chat_type=wpa&uin=" + qq + "&version=1&src_type=web&web_src=oicqzone.com");
        }
    }
</script>
</body>
</html>