<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no"/>
    <title>盒子下载</title>
</head>
<body>
<div style="text-align: center">
    恭喜你获得返利资格和贵宾礼包请下载盒子领取      <br/>
↓<br/>
↓<br/>
<a href="<?=$url?>">立即下载</a><br/>
    <br/>

   <a onclick="copyUrl()" href="#"> 部分手机无法下载请点击复制链接到浏览器下载</a>
    <br/>
    <textarea id="mytext" style="width: 350px;height: 30px;"><?=$url?></textarea>

</div>
<script src="/js/jquery-zclip/jquery.zclip.js"></script>
<script>
    function copyUrl() {
        var Url2 = document.getElementById("mytext");
        Url2.select(); // 选择对象
        document.execCommand("Copy"); // 执行浏览器复制命令
        alert("已复制好，可贴粘到浏览器下载。");
    }
</script>
</body>
</html>