<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no"/>
    <title>盒子下载</title>
</head>
<body>
<div style="text-align: center">
    联系客服领取礼包
<!--下载盒子领取贵宾礼包      <br/>-->
<!--↓<br/>-->
<!--↓<br/>-->
<!--<a href="--><?//=$url?><!--">立即下载</a>-->
</div>
</body>
</html>