<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no"/>
    <title>客服中心</title>
    <link rel="stylesheet" href="/public/styles/base.css"/>
    <link rel="stylesheet" href="/styles/pay_edit.css"/>
    <link rel="stylesheet" href="/layui/css/layui.css"/>
    <style>
        a{color: #0b0b0b!important;text-decoration:underline}
        .layui-input-block {
             margin-left: 0!important;
            min-height: 36px;
        }
    </style>
</head>
<body style="background-color:#ffffff">
<!--div.container 总外框  start-->
<div>
<!--    <blockquote class="layui-elem-quote layui-quote-nm"></blockquote>-->
    <div style="height: 38px;line-height: 38px">在线提交申请返利或游戏问题</div>
    <form class="layui-form" action="/index/sdkapi/feedbackAdd" method="post">
        <div class="layui-form-item">
            <div class="layui-input-block">
                <select name="type" lay-verify="required" lay-filter="type" id="type" >
                    <option value="">选择提交分类</option>
                    <?php foreach ($types as $tp) { ?>
                        <option value="<?= $tp ?>"><?= $tp ?></option>
                    <?php } ?>
                </select>
            </div>
        </div>
        <div class="layui-form-item">
            <div class="layui-input-block">
                <input type="text" id="title" name="title"   lay-verify="required" placeholder="请输入标题" autocomplete="off" class="layui-input" maxlength="15">
            </div>
        </div>
        <div class="layui-form-item layui-form-text">
            <div class="layui-input-block">
                <textarea id="reply" name="content" placeholder="请输入内容" class="layui-textarea" ></textarea>
            </div>
        </div>
        <div class="layui-form-item">
            <div class="layui-input-block">
                <input type="hidden" id="user_id" name="user_id" value="<?=$info['uid']?>">
                <button id="btn" type="submit"  class="layui-btn layui-btn-fluid" lay-submit lay-filter="formDemo">在线提交</button>
            </div>
        </div>
        <div class="layui-form-item">
            <div class="layui-input-block" style="text-align: center">
                <a href="/index/sdkapi/feedbacklist?uid=<?=$info['uid']?>" >我已提交的点击查看</a>
            </div>
        </div>
    </form>
    <div style="float: left">
<!--        <image src="/images/login/qq.png" width="20" height="20"></image>-->
        <a onclick="jump_qq(this)" data-id="<?= $info['service_qq'] ?>" href="javascript:void(0);">客服QQ:<?= $info['service_qq']; ?></a>
    </div>
        <div style="float: right;margin-bottom: 12px">
<!--            <image src="/images/login/qq.png" width="20" height="20"></image>-->
            <a onclick="jump_qq(this)" data-id="<?= $info['service_qq2'] ?>" href="javascript:void(0);">玩家QQ群:<?= $info['service_qq2']; ?></a>
        </div>
</div>
<!--div.container 总外框  end-->
<script src="/public/scripts/jquery-1.11.1.min.js"></script>
<script src="/public/scripts/jquery.mobile.min.js"></script>
<script src="/layui/layui.js"></script>
<script>
    layui.use(['layer', 'form','layedit'], function(){
        var form = layui.form,layedit = layui.layedit;
        layedit.set({
            uploadImage: {
                url: '/index/sdkapi/uploadReplyImg' //接口url
                ,type: '' //默认post
            }
        });
        var index =layedit.build('reply'); //建立编辑器
        form.on('submit(formDemo)', function(data){
            var value=layedit.getContent(index);
            if(value=='')return false;
        });
        form.on('select(type)', function(data){
            console.log(111);
            var html='';
            var value=data.value;
            console.log(111);
            switch (value) {
                case '游戏问题':
                    html='游戏名字：<br/>' +
                        '游戏账号：<br/>' +
                        '密码：尽量有<br/>' +
                        '区服：<br/>' +
                        '角色名字：<br/>' +
                        '充值金额：<br/>' +
                        '充值时间：<br/>' +
                        '问题描述：';
                    break;
                // case '代理问题':
                //     html=''
                //     break;
                case '申请返利':
                    html='游戏名字：<br/>' +
                        '游戏账号：<br/>' +
                        '区服：<br/>' +
                        '角色名字：<br/>' +
                        '角色ID:游戏内点击角色头像查看或游戏内点击设置查看<br/>' +
                        '充值金额：<br/>' +
                        '充值时间：<br/>' +
                        '备注：';
                    break;
                case '其他问题':
                    html='';
                    break;
                default:
                    html='';
                    break;
            }
            layedit.setContent(index,html);
            // $('#content').html(html);
        });
    });
    function IsPC() {
        var userAgentInfo = navigator.userAgent;
        var Agents = ["Android", "iPhone",
            "SymbianOS", "Windows Phone",
            "iPad", "iPod"];
        var flag = true;
        for (var v = 0; v < Agents.length; v++) {
            if (userAgentInfo.indexOf(Agents[v]) > 0) {
                flag = false;
                break;
            }
        }
        return flag;
    }
    function jump_qq(obj) {
        var qq = $(obj).attr('data-id');
        if (IsPC()) {
            window.open("http://wpa.qq.com/msgrd?v=3&uin=" + qq + "&site=qq&menu=yes");
        } else {
            window.open("mqqwpa://im/chat?chat_type=wpa&uin=" + qq + "&version=1&src_type=web&web_src=oicqzone.com");
        }
    }
</script>
</body>
</html>