<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no"/>
    <title>客服中心</title>
    <link rel="stylesheet" href="/public/styles/base.css"/>
    <link rel="stylesheet" href="/styles/pay_edit.css"/>
</head>
<body style="background-color:#ffffff">
<!--div.container 总外框  start-->
<div>
        <div>客服QQ:<?=$info['service_qq'];?></div>
        <div>QQ群:<?=$info['service_qq2'];?></div>
        <div>投诉电话：只接受投诉游戏问题：:17190306112</div>
</div>
<!--div.container 总外框  end-->
<script src="/public/scripts/jquery-1.11.1.min.js"></script>
<script src="/public/scripts/jquery.mobile.min.js"></script>
</body>
</html>