<?php foreach ($servers as $row) : ?>
<li>
    <section class="list_content">
        <div class="game_log relative">
            <a target="_top" href="javascript:void(0);"><img src="<?=$row['logo']?>" width="60" height="60" alt="<?=$row['game_name']?>"></a>
        </div>
        <div class="game_info">
            <h3>
                <span><a target="_top" href="javascript:void(0);" style="color:#fff;"><?=$row['game_name']?></a></span>
            </h3>
            <p><?=$row['name']?></p>
                <p>开服时间：<?=$row['start_time']?></p>
        </div>
        <?php if($row['giftbag']):?>
            <a href="/game/giftbag.html?gift_id=<?=$row['giftbag']?>" class="icons i_lb"></a>
        <?php endif;?>
        <div class="game_btn">
            <?php if($row['game_type']=='手游'):?>
                    <a target="_top" onclick="countDownload(this,100)" href="<?='http://yun.zyttx.com/index/apkgame?game_id='.$row['game_id'].'&tg_channel='.$tg_channel?>" class="btn_blue">点击下载</a>
            <?php else:?>
                <a target="_top" href="/game/play.html?game_id=<?=$row['game_id']?>" class="btn_blue">开始玩</a>
            <?php endif;?>
        </div>
    </section>
</li>
<?php endforeach; ?>
