<!DOCTYPE html>
<html>
<head lang="en">
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" />
<meta name="screen-orientation" content="portrait">
<meta name="keywords" content="公益服,手游公益服,bt手游,gm手游">
<meta name="description" content="公益服第一门户站,聚合全网无限元宝公益服,手游公益服,bt手游,gm手游下载,提供有趣有态度的最新手游内容,汇聚手游社区,热门手游礼包,攻略,手游排行榜等,让你体验最新H5游戏、无限元宝的乐趣">
<title>BT手游-满VIP版手游-GM版手游无限元宝-久乐游戏</title>
<link rel="stylesheet" href="/public/styles/base.css"/>
<link rel="stylesheet" href="/styles/index.css"/>
</head>
<body class="bg00">
    <!--div.container 总外框  start-->
    <div data-role="page" class="z_container bg01">
        <!--div.z_min 内容区域 statr-->
        <div class="z_main" data-role="conent">
            <div class="banner" id="banner_silider">
                <ul>
                <?php foreach ($banner['ads'] as &$row) { ?>
                    <li>
                        <a href="<?=$row['url']?>" class="line_01">
                            <img src="<?=$row['image']?>" width="100%" height="auto"<?php if($row['subject']) echo " alt=\"{$row['subject']}\""; ?>/>
                        </a>
                    </li>
                <?php } ?>
                </ul>
            </div>
            <nav class="play_list">
<!--                <i class="icons logo"></i>-->
                <ul class="ui-grid-d" id="list_nav">
                <?php $i = 0; foreach ($games as $type=>&$row) { ?>
                    <li<?php echo $i==0 ? ' class="list_active"' : ''; ++$i; ?>><?=$type?></li>
                <?php } ?>
                </ul>
            </nav>

            <!--div.game_list 游戏列表  start-->
            <section class="game_list" id="game_list">
                <div class="slide_cont">
                <?php $i = 1; foreach ($games as $type=>&$list) { ?>
                    <!--ui#game_list_<?=$i?> <?=$type?>游戏列表  start-->
                    <ul id="game_list_<?=$i?>">
                    <?php foreach ($list as &$row) { ?>
                        <li>
                            <?php if($row['corner'] != 'normal') { ?>
                            <i class="icons i_<?=$row['corner']?>"></i>
                            <?php } ?>
                            <section class="list_content">
                                <div class="game_log relative">
                                    <a target="_top" href="/game/detail.html?game_id=<?=$row['game_id']?>"><img src="<?=$row['logo']?>" width="100%" height="auto" alt="<?=$row['name']?>"></a>
                                </div>
                                <div class="game_info">
                                    <h3>
                                        <span><a target="_top" href="/game/detail.html?game_id=<?=$row['game_id']?>" title="<?=$row['name']?>" style="color:#fff;"><?=$row['name']?></a></span>
                                    <?php if($row['label'] != 'normal') { ?>
                                        <i class="icons <?=$row['label']?>"></i>
                                    <?php } ?>
                                    </h3>
                                    <P>
                                    <span class="start_list fl">
                                        <?=$row['grade']?>
                                    </span>
                                        <span>人气：<?=$row['support']?></span>
                                    </P>
                                    <p><?=$row['in_short']?></p>
                                </div>
                                <?php if($row['giftbag']) { ?>
                                <a href="/game/giftbag.html?gift_id=<?=$row['giftbag']?>" class="icons i_lb"></a>
                                <?php } ?>
                                <div class="game_btn">
                                    <?php if($row['game_type']=='手游'):?>
                                            <a target="_top" onclick="countDownload(<?=$row['game_id'];?>)" href="<?='http://yun.zyttx.com/index/apkgame?game_id='.$row['game_id'].'&tg_channel='.$tg_channel?>" class="btn_blue">点击下载</a>
                                    <?php else:?>
                                        <a target="_top" href="/game/play.html?game_id=<?=$row['game_id']?>" class="btn_blue">开始玩</a>
                                    <?php endif;?>
                                </div>
                            </section>
                        </li>
                        <?php } ?>
                    </ul>
                    <!--ui#game_list_<?=$i?> <?=$type?>游戏列表  end-->
                <?php ++$i; } ?>
                </div>
            </section>
            <!--div.game_list 游戏列表  end-->

            <!--div.game_news 快速通道  statr-->
            <section class="game_news">
                <h2 class="title">
                    <span class="title_name"> <i class="icons i_hand"></i>快速通道</span>
                </h2>
                <div class="block_bg recommend">
                    <a href="/game/center.html">
                    <div>
                        <img src="/images/index/游戏分类.png"  height="auto" alt="游戏分类" />
                        <br/>
                        <span>游戏分类</span>
                    </div>
                    </a>
<!--                    <a href="--><?//=empty($user)?'/user/login.html?fwd=':''?><!--/info/index.html">-->
                        <a href="/info/index.html">
                        <div>
                        <img src="/images/index/活动福利.png" height="auto" alt="活动福利" />
                        <br/>
                        <span>活动福利</span>
                    </div>
                    </a>
                    <a href="/game/server?tc=0">
                    <div>
                        <img src="/images/index/开服详情.png"  height="auto" alt="开服详情" />
                        <br/>
                        <span>开服详情</span>
                    </div>
                    </a>
<!--                    <a href="/info/index.html">-->
<!--                    <div>-->
<!--                        <img src="/images/index/活动资讯.png"  height="auto" alt="活动资讯" />-->
<!--                        <br/>-->
<!--                        <span>活动资讯</span>-->
<!--                    </div>-->
<!--                    </a>-->
                    <?php
                    //优先使用域名判断
                    $url=new F_Helper_Url();
                    $g=$url->getUrlSign();
                    ?>
                        <a   href="<?='http://yun.zyttx.com/index/apkgame3?&tg_channel='.$g?>">
                            <div>
                                <img src="/images/index/盒子下载.png"  height="auto" alt="盒子下载" />
                                <br/>
                                <span>安卓盒子</span>
                            </div>
                        </a>
                    <a   href="<?='http://yun.zyttx.com/index/apkgame4?&tg_channel='.$g?>">
                        <div>
                            <img src="/images/index/盒子下载苹果.png"  height="auto" alt="盒子下载苹果" />
                            <br/>
                            <span>苹果盒子</span>
                        </div>
                    </a>
                </div>
            </section>
            <!--div.game_news 快速通道  end-->
            <!--figure.game_figure vip俱乐部  statr-->
<!--            <figure class="game_figure">-->
<!--                --><?php //if(file_exists("/www2/wwwroot/xgame.zyttx.com/apk/{$g}.apk")):?>
<!--                    <a   href="--><?//="http://xgame.zyttx.com/apk/{$g}.apk"?><!--">-->
<!--                        --><?php //foreach ($shortcut['ads'] as &$row) :?>
<!--                        <img src="--><?//=$row['image']?><!--" width="100%" height="auto" alt="--><?//=$row['subject']?><!--"/>-->
<!--                        --><?php //endforeach;?>
<!--                    </a>-->
<!--                --><?php //else:?>
<!--                    <a   href="--><?//='http://yun.zyttx.com/index/akpgame2?&tg_channel='.$g?><!--">-->
<!--                        --><?php //foreach ($shortcut['ads'] as &$row) :?>
<!--                        <img src="--><?//=$row['image']?><!--" width="100%" height="auto" alt="--><?//=$row['subject']?><!--"/>-->
<!--                        --><?php //endforeach;?>
<!--                    </a>-->
<!--                --><?php //endif;?>
<!--            </figure>-->
            <!--figure.game_figure vip俱乐部  end-->
            <!--section.game_news hot 火爆新游  statr-->
            <section class="game_news">
                <h2 class="title">
                    <span class="title_name"> <i class="icons i_fire"></i>火爆新游</span>
                    <a class="more" href="/game/type.html?tc=全部分类">更多 &gt;</a>
                </h2>
<!--                <div class="scroll_cont">-->
<!--                    <nav class="block_bg nav_img">-->
<!--                    --><?php //foreach ($hotnew['ads'] as &$row) { ?>
<!--                        <a href="--><?//=$row['url']?><!--">-->
<!--                            <img src="--><?//=$row['image']?><!--" width="50" height="50" alt="--><?//=$row['subject']?><!--">-->
<!--                            <h4>--><?//=$row['subject']?><!--</h4>-->
<!--                        </a>-->
<!--                    --><?php //} ?>
<!--                    </nav>-->
<!--                </div>-->
                <section class="game_list">
                    <div>
                            <ul>
                                <?php foreach ($new_games as &$row) { ?>
                                    <li>
                                        <?php if($row['corner'] != 'normal') { ?>
                                            <i class="icons i_<?=$row['corner']?>"></i>
                                        <?php } ?>
                                        <section class="list_content">
                                            <div class="game_log relative">
                                                <a target="_top" href="/game/detail.html?game_id=<?=$row['game_id']?>"><img src="<?=$row['logo']?>" width="100%" height="auto" alt="<?=$row['name']?>"></a>
                                            </div>
                                            <div class="game_info">
                                                <h3>
                                                    <span><a target="_top" href="/game/detail.html?game_id=<?=$row['game_id']?>" title="<?=$row['name']?>" style="color:#fff;"><?=$row['name']?></a></span>
                                                    <?php if($row['label'] != 'normal') { ?>
                                                        <i class="icons <?=$row['label']?>"></i>
                                                    <?php } ?>
                                                </h3>
                                                <P>
                                    <span class="start_list fl">
                                        <?=$row['grade']?>
                                    </span>
                                                    <span>人气：<?=$row['support']?></span>
                                                </P>
                                                <p><?=$row['in_short']?></p>
                                            </div>
                                            <?php if($row['giftbag']) { ?>
                                                <a href="/game/giftbag.html?gift_id=<?=$row['giftbag']?>" class="icons i_lb"></a>
                                            <?php } ?>
                                            <div class="game_btn">
                                                <?php if($row['game_type']=='手游'):?>
                                                        <a target="_top"  onclick="countDownload(<?=$row['game_id'];?>)"  href="<?='http://yun.zyttx.com/index/apkgame?game_id='.$row['game_id'].'&tg_channel='.$tg_channel?>" class="btn_blue">点击下载</a>
                                                <?php else:?>
                                                    <a target="_top" href="/game/play.html?game_id=<?=$row['game_id']?>" class="btn_blue">开始玩</a>
                                                <?php endif;?>
                                            </div>
                                        </section>
                                    </li>
                                <?php } ?>
                            </ul>
                    </div>
                </section>
            </section>
            <!--section.game_news 今日推荐  end-->

            <!--section.game_news action 最新活动  statr-->
            <section class="game_news action">
                <h2 class="title">
                    <span class="title_name"> <i class="icons i_action"></i>最新活动</span>
                    <a class="more" href="/info/index">更多 &gt;</a>
                </h2>
<!--            --><?php //foreach ($activity['ads'] as $row) { ?>
<!--                <div class="actions">-->
<!--                    <a href="--><?//=$row['url']?><!--">-->
<!--                        <img src="--><?//=$row['image']?><!--"--><?//=$row['subject']?" alt=\"{$row['subject']}\"":''?><!-- style="width:100%">-->
<!--                    </a>-->
<!--                </div>-->
<!--            --><?php //} ?>
                <ul class="game_news2">
                    <?php foreach ($info as &$row) { ?>
                        <li>
                            <?php if( $row['cover'] ) { ?>
                                <a href="/info/detail.html?type=<?=$type?>&article_id=<?=$row['article_id']?>"><img src="<?=$row['cover']?>" width="90" height="auto" alt="<?=$row['title']?>"/></a>
                            <?php } ?>
                            <article>
                                <p><a href="/info/detail.html?type=<?=$type?>&article_id=<?=$row['article_id']?>"><?=$row['title']?></a></p>
                                <div>
                                    <span><?=$row['up_time']?></span>
                                </div>
                            </article>
                        </li>
                    <?php } ?>
                </ul>
            </section>
            <!--section.game_news action 最新活动  end-->

            <!--<div class="footer_zoom"></div>-->
            <div class="footer_padding"></div>
        </div>
        <!--div.z_min 内容区域 end-->
    </div>
    <!--div.container 总外框  end-->
<?php include $this->getScriptPath().'/footer.phtml'; ?>
<script src="/public/scripts/jquery-1.11.1.min.js"></script>
<script src="/public/scripts/jquery.mobile.min.js"></script>
<script src="/jquery/swipe.js"></script>
<script>
$('#footer a:eq(0)').attr('id', 'footer_nav_active');
$(function(){
	var banner_slider = new Swipe(document.getElementById('banner_silider'), {
	  startSlide: 0,
	  speed: 400,
	  auto: 3000,
	  continuous: true
	});
	$('#banner_silider').css('height','auto');

	var game_slider = new Swipe(document.getElementById('game_list'), {
	  startSlide: 0,
	  speed: 400,
	  auto: false,
	  callback: function(index, elem) {
		  $('#list_nav li').removeClass('list_active').eq(index).addClass('list_active');
	  }
	});
	$('#list_nav li').on('tap', function(){
		game_slider.slide($(this).index(), 400);
		return true;
	});
	$('.slide_cont ul').height($('.slide_cont').height());

	function getWidth(){
	    var childLen = $(".nav_img a").length;
	    var childWidth = $(".nav_img a").outerWidth();
	    var widowWidth = $(window).width(); //窗口宽度
	    var allWidth = childLen * childWidth; //计算后总宽度
	    /**宽度不能小于100%*/
	    if(allWidth < widowWidth){
	        $(".nav_img").width(widowWidth);
	    }else{
	        $(".nav_img").width(allWidth);
	    }
	}
	getWidth();
	window.onorientationchange=window.onresize=function(){
        getWidth();
    };
	//判断是否是安卓端，提示更新新版盒子

});
</script>
    <script type="text/javascript">
        function isapp() {
            if (/^.+(Mobile\/\w+)\s?$/.test(navigator.userAgent)) {
                    // 端APP
                    console.log('app');
                // $.confirm({
                //     title: '确认',
                //     content: '确认把该搜索结果导出Excel表格?',
                //     type: 'green',
                //     icon: 'glyphicon glyphicon-question-sign',
                //     buttons: {
                //         ok: {
                //             text: '确认',
                //             btnClass: 'btn-primary',
                //             action: function() {
                //                 location.href = url; //指向下载资源（此处为目标文件的输出数据流）
                //             }
                //         },
                //         cancel: {
                //             text: '取消',
                //             btnClass: 'btn-primary'
                //         }
                //     }
                // });
                return true;
            } else {
                    // 端浏览器
                    console.log('web');
                return false;
            }
        }
    </script>
</body>
</html>