<!DOCTYPE html>
<!-- saved from url=(0028)http://c.91vv.com/index.html -->
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <title>CPS公会合作</title>
    <link href="/index/Global.Css" rel="stylesheet" type="text/css">
    <link href="/index/Index.Css" rel="stylesheet" type="text/css">
    <style>
        #news {
            height: 2rem;
            overflow: hidden;
            /*border: solid 1px #29ba67;*/
            text-align: center;
        }
    </style>
</head>
<body>
<!-- 导航 -->
<div class="Head-Menu">
    <div class="m1200">
<!--        <a href="#" class="logo"></a>-->

        <div class="Login-Box Login-Pop"><a href="javascript:void(0)">登录后台</a></div>
        <div class="Register-Box Register-Pop"><a href="javascript:void(0)">注册加盟</a></div>
        <div class="User-Box">欢迎<span>OeYoFee</span>登录平台<a href="javascript:void(0)">进入平台</a><a
                    class="User-Show" href="javascript:void(0)">退出登录</a></div>
    </div>
</div>
<!-- 导航end -->
<!-- 游戏广告图 -->
<div class="lubo">
    <ul class="lubo_box Login-Pop">
        <li style="opacity: 1;">
            <img src="/index/Images/banner1.jpg" width="100%" height="100%"/>
        </li>
    </ul>
    <ul class="cir_box" style="left: 50%; margin-left: -35px; bottom: 5%;">
        <li style="" value="0" class=""></li>
    </ul>
    <div class="lubo_btn">
        <div class="left_btn l">&lt;</div>
        <div class="right_btn r">&gt;</div>
    </div>
</div>
<!-- 游戏广告图end -->
<div class="Index-Platform">
    <div class="Instructions">
        <ul>
            <li>
                <div class="Function-Name">
                    <em class="Pic-Two"></em>
                    <h1>专属APP盒子</h1>
                    <p>APP盒子,安卓+IOS高效留存</p>
                </div>
                <div class="Detail-Box">
                    <h1>专属APP盒子<em></em></h1>
                    <p>● 专属APP盒子</p>
                    <p>● 安卓+IOS。</p>
                    <p>● 高效留存用户。</p>
                    <i class="Pic-Two"></i>
                </div>
            </li>
            <li>
                <div class="Function-Name">
                    <em class="Pic-Three"></em>
                    <h1>专属网站</h1>
                    <p>拥有专属网站,省事省心省力</p>
                </div>
                <div class="Detail-Box">
                    <h1>专属网站<em></em></h1>
                    <p>● 拥有专属网站</p>
                    <p>● 省事省心省力。</p>
                    <p>● 新产品自动更新上架。</p>
                    <i class="Pic-Three"></i>
                </div>
            </li>
            <li>
                <div class="Function-Name">
                    <em class="Pic-Four"></em>
                    <h1>收益结算速度快</h1>
                    <!--<p>完整精确的流水数据、后台自助申请</p>-->
                    <p>T+1结算模式,收益有保障</p>
                </div>
                <div class="Detail-Box">
                    <h1>收益速度快<em></em></h1>
                    <p>T+1结算模式,收益有保障</p>
                    <i class="Pic-Four"></i>
                </div>
            </li>
        </ul>
    </div>
</div>

<div class="Game-Box">
<!--    <div class="Title"></div>-->
    <div class="Game-Icon">
        <ul>
            <li><img src="/index/01.png" width="126" height="126" alt=""></li>
            <li><img src="/index/02.png" width="126" height="126" alt=""></li>
            <li><img src="/index/03.png" width="126" height="126" alt=""></li>
            <li><img src="/index/04.png" width="126" height="126" alt=""></li>
            <li><img src="/index/05.png" width="126" height="126" alt=""></li>
            <li><img src="/index/06.png" width="126" height="126" alt=""></li>
            <li><img src="/index/07.png" width="126" height="126" alt=""></li>
            <li><img src="/index/08.png" width="126" height="126" alt=""></li>
            <li><img src="/index/09.png" width="126" height="126" alt=""></li>
            <li><img src="/index/10.png" width="126" height="126" alt=""></li>
            <li><img src="/index/11.png" width="126" height="126" alt=""></li>
            <li><img src="/index/12.png" width="126" height="126" alt=""></li>
        </ul>
    </div>
</div>

<div class="Access">
    <h1><a class="Register-Pop" href="javascript:void(0)">立即合作</a></h1>
</div>
<!-- 版权 -->
<div class="Copyright">
</div>
<!-- 版权end -->


<div class="goodcover"></div>
<div class="code">
    <div class="Shut closebt"><a href="javascript:void(0)"></a></div>
    <form class="Login" id="LoginForm">
        <h1>账户登录</h1>
        <div class="Form Account form-group u">
            <input class="Input username" type="text" placeholder="账户" name="username">
        </div>
        <div class="Form PasswordBox form-group p">
            <input id="password" class="password Input form-control" type="password" placeholder="密码" name="password">
        </div>
        <div class="Form Verification form-group y">
            <input class="Input-Code tel" type="text" maxlength="4" placeholder="请输入验证码" name="captcha">
            <div>
                <img src="<?= 'index/index/getVerify?id=login' ?>" alt="captcha"
                      onclick="refreshVerify(this,'login')" class="login_captcha"/></div>
        </div>
        <div class="Login-Link submit"><a id="loginBtn" href="javascript:void(0)">立即登录</a></div>
        <div class="Register-Box Register-Pop" style="float: right"><a href="javascript:void(0)"><span>没有账号？点击</span>注册</a>
        </div>
    </form>
</div>
<div class="code2">
    <div class="Shut closebt2"><a href="javascript:void(0)"></a></div>
    <form class="Register Login" id="RegisterForm">
        <h1>账户注册</h1>
        <div class="Form Account form-group u">
            <input class="Input username" type="text" placeholder="账户 6-25位字母数字或下划线组成" name="username">
        </div>
        <div class="Form PasswordBox form-group p">
            <input class="Input register_password form-control" type="password" placeholder="密码 6-20个字符"
                   name="password">
        </div>
        <div class="Form PasswordBox form-group p">
            <input class="Input password form-control" type="password" placeholder="确认密码 6-20个字符" name="repassword">
        </div>
        <div class="Form Verification form-group y">
            <input name="captcha" class="Input-Code tel" type="tel" maxlength="4" placeholder="请输入验证码">
            <div><img class="register_captcha" src="<?= 'index/index/getVerify?id=register' ?>" alt="captcha"
                      onclick="refreshVerify(this,'register')"/></div>
        </div>
        <input type="hidden" name="parent_id" value="<?= $channel_id?>">
        <div class="Login-Link submit"><a id="RegisterBtn" type="submit">立即注册</a></div>
    </form>
</div>
<script src="/index/jquery.min.js"></script>
<script src="/index/jquery.validate.min.js"></script>
<script src="/index/Index.js"></script>
<script src="/index/jquery.touchSlider.js"></script>
</body>
</html>