<!DOCTYPE html>
<!-- saved from url=(0028)http://c.91vv.com/index.html -->
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <title>游戏推广平台</title>
    <link href="/static/index/Global.Css" rel="stylesheet" type="text/css">
    <link href="/static/index/Index.Css" rel="stylesheet" type="text/css">
    <style>
        #news {
            height: 1rem;
            overflow: hidden;
            /*border: solid 1px #29ba67;*/
            text-align: center;
        }
    </style>
</head>
<body>
<!-- 导航 -->
<div class="Head-Menu">
    <div class="m1200">
        <a href="#" class="logo"></a>
        <ul class="nav" style="margin-left: 14px;">
             <li><a href="<?=url('index/index/index')?>" class="on">首页</a></li>
             <li><a href="<?=url('index/index/index2')?>" >平台优势</a></li>
             <li><a href="<?=url('index/index/index3')?>" >如何推广</a></li>
             <li><a href="<?=url('index/index/index4')?>">商务合作</a></li>
        </ul>
        <div class="Login-Box Login-Pop"><a href="javascript:void(0)">登录推广后台</a></div>
        <div class="Register-Box Register-Pop"><a href="javascript:void(0)">立刻注册代理</a></div>
        <div class="User-Box">欢迎<span>OeYoFee</span>登录游戏推广平台<a href="javascript:void(0)">进入推广平台</a><a
                    class="User-Show" href="javascript:void(0)">退出登录</a></div>
    </div>
</div>
<!-- 导航end -->
<div class="Index-Platform">
    <div class="Version">
        <div class="demo1 Font-Box" id="news">
            <span style="float: left;">代理提现:</span>
            <ul style="float: left;">
                <li>代理账号 67***170今日提现20050</li>
                <li>代理账号 34****28094今日提现9050</li>
                <li>代理账号 cui****hao56今日提现8891</li>
                <li>代理账号 534***2388今日提现17891</li>
                <li>代理账号 s13***146今日提现5002</li>
                <li>代理账号 189***25今日提现12351</li>
                <li>代理账号 wzy***67今日提现3345</li>
                <li>代理账号 764***09今日提现2671</li>
                <li>代理账号 sta***ng今日提现1355</li>
                <li>代理账号 980***90今日提现112233</li>
                <li>代理账号 star***u*in今日提现8891</li>
                <li>代理账号 378***46今日提现41350</li>
                <li>代理账号 ps***990今日提现33668</li>
                <li>代理账号 86***472今日提现24197.2</li>
                <li>代理账号 12***043今日提现6372</li>
                <li>代理账号 a4***00今日提现 2578</li>
                <li>代理账号 132***59553今日提现3324.6</li>
                <li>代理账号 754***80今日提现61362.2</li>
                <li>代理账号 1261***38今日提现6246.2</li>
                <li>代理账号 83***388今日提现4464.4</li>
                <li>代理账号 a57***51今日提现2316.4</li>
                <li>代理账号 435***03097今日提现9575.2</li>
                <li>代理账号 180***4405今日提现3702.2</li>
                <li>代理账号 103***313719今日提现11121.6</li>
                <li>代理账号 589***235iao今日提现6151.6</li>
                <li>代理账号 168***604828今日提现4139.2</li>
                <li>代理账号 162***761347今日提现3312</li>
                <li>代理账号 769***0075070今日提现2111</li>
                <li>代理账号 a10***75今日提现2316</li>
                <li>代理账号 a10***8926lin0今日提现6633.2</li>
                <li>代理账号 151***527735今日提现1964.4</li>
                <li>代理账号 Kelly***251今日提现4256</li>
                <li>代理账号 344***51今日提现7200</li>
                <li>代理账号 17***99998今日提现7199.6</li>
                <li>代理账号 az***ai14648今日提现3129.6</li>
                <li>代理账号 nht***01今日提现66619.6</li>
                <li>代理账号 246***68今日提现51137.6</li>
                <li>代理账号 ti***yy今日提现22208</li>
                <li>代理账号 miu***0718今日提现3313.2</li>
                <li>代理账号 ccv***ao8今日提现2217.2</li>
                <li>代理账号 681***68今日提现9373.8</li>
                <li>代理账号 575***80今日提现8886</li>
                <li>代理账号 368***47今日提现4412</li>
                <li>代理账号 Pf1***7892今日提现6613.2</li>
                <li>代理账号 400***30今日提现3565</li>
                <li>代理账号 763***54今日提现1458</li>
                <li>代理账号 615***66今日提现3798</li>
                <li>代理账号 86***52今日提现12073.8</li>
                <li>代理账号 14***804今日提现1557</li>
            </ul>
        </div>
    </div>
    <div class="Title"></div>

    <div class="Instructions">
        <div class="content">

        </div>
    </div>
</div>
<script src="/static/index/jquery.min.js"></script>
<script src="/static/index/jquery.validate.min.js"></script>
<script src="/static/index/Index.js"></script>
<script src="/static/index/jquery.touchSlider.js"></script>
</body>
</html>