<!DOCTYPE html>
<!-- saved from url=(0028)http://c.91vv.com/index.html -->
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <title>游戏推广平台</title>
    <link href="/static/index/Global.Css" rel="stylesheet" type="text/css">
    <link href="/static/index/Index.Css" rel="stylesheet" type="text/css">
    <style>
        #news {
            height: 1rem;
            overflow: hidden;
            /*border: solid 1px #29ba67;*/
            text-align: center;
        }
    </style>
</head>
<body>
<!-- 导航 -->
<div class="Head-Menu">
    <div class="m1200">
        <a href="#" class="logo"></a>
        <div class="Login-Box Login-Pop"><a href="javascript:void(0)">登录推广后台</a></div>
        <div class="Register-Box Register-Pop"><a href="javascript:void(0)">立刻注册代理</a></div>
        <div class="User-Box">欢迎<span>OeYoFee</span>登录游戏推广平台<a href="javascript:void(0)">进入推广平台</a><a
                    class="User-Show" href="javascript:void(0)">退出登录</a></div>
    </div>
</div>
<!-- 导航end -->
<!-- 游戏广告图 -->
<div class="lubo">
    <ul class="lubo_box Login-Pop">
        <li style="opacity: 0;"><a href="javascript:void(0)" style="background:url(/static/index/Images/banner1.jpg) center top no-repeat"></a>
        </li>
        <li style="opacity: 1;"><a href="javascript:void(0)" style="background:url(/static/index/Images/banner2.jpg) center top no-repeat"></a>
        </li>
        <li><a href="javascript:void(0)" style="background:url(/static/index/Images/banner3.jpg) center top no-repeat"></a></li>
    </ul>
    <ul class="cir_box" style="left: 50%; margin-left: -35px; bottom: 5%;">
        <li style="" value="0" class=""></li>
        <li style="" value="1" class=""></li>
        <li style="" value="2" class=""></li>
    </ul>
    <div class="lubo_btn">
        <div class="left_btn l">&lt;</div>
        <div class="right_btn r">&gt;</div>
    </div>
</div>
<!-- 游戏广告图end -->
<div class="Index-Platform">
    <div class="Version">
        <div class="demo1 Font-Box" id="news">
            <span style="float: left;">代理提现:</span>
            <ul style="float: left;">
                <li>代理账号 67***170今日提现20050</li>
                <li>代理账号 34****28094今日提现9050</li>
                <li>代理账号 cui****hao56今日提现8891</li>
                <li>代理账号 534***2388今日提现17891</li>
                <li>代理账号 s13***146今日提现5002</li>
                <li>代理账号 189***25今日提现12351</li>
                <li>代理账号 wzy***67今日提现3345</li>
                <li>代理账号 764***09今日提现2671</li>
                <li>代理账号 sta***ng今日提现1355</li>
                <li>代理账号 980***90今日提现112233</li>
                <li>代理账号 star***u*in今日提现8891</li>
                <li>代理账号 378***46今日提现41350</li>
                <li>代理账号 ps***990今日提现33668</li>
                <li>代理账号 86***472今日提现24197.2</li>
                <li>代理账号 12***043今日提现6372</li>
                <li>代理账号 a4***00今日提现 2578</li>
                <li>代理账号 132***59553今日提现3324.6</li>
                <li>代理账号 754***80今日提现61362.2</li>
                <li>代理账号 1261***38今日提现6246.2</li>
                <li>代理账号 83***388今日提现4464.4</li>
                <li>代理账号 a57***51今日提现2316.4</li>
                <li>代理账号 435***03097今日提现9575.2</li>
                <li>代理账号 180***4405今日提现3702.2</li>
                <li>代理账号 103***313719今日提现11121.6</li>
                <li>代理账号 589***235iao今日提现6151.6</li>
                <li>代理账号 168***604828今日提现4139.2</li>
                <li>代理账号 162***761347今日提现3312</li>
                <li>代理账号 769***0075070今日提现2111</li>
                <li>代理账号 a10***75今日提现2316</li>
                <li>代理账号 a10***8926lin0今日提现6633.2</li>
                <li>代理账号 151***527735今日提现1964.4</li>
                <li>代理账号 Kelly***251今日提现4256</li>
                <li>代理账号 344***51今日提现7200</li>
                <li>代理账号 17***99998今日提现7199.6</li>
                <li>代理账号 az***ai14648今日提现3129.6</li>
                <li>代理账号 nht***01今日提现66619.6</li>
                <li>代理账号 246***68今日提现51137.6</li>
                <li>代理账号 ti***yy今日提现22208</li>
                <li>代理账号 miu***0718今日提现3313.2</li>
                <li>代理账号 ccv***ao8今日提现2217.2</li>
                <li>代理账号 681***68今日提现9373.8</li>
                <li>代理账号 575***80今日提现8886</li>
                <li>代理账号 368***47今日提现4412</li>
                <li>代理账号 Pf1***7892今日提现6613.2</li>
                <li>代理账号 400***30今日提现3565</li>
                <li>代理账号 763***54今日提现1458</li>
                <li>代理账号 615***66今日提现3798</li>
                <li>代理账号 86***52今日提现12073.8</li>
                <li>代理账号 14***804今日提现1557</li>
            </ul>
        </div>
    </div>
    <div class="Title"></div>

    <div class="Instructions">
        <ul>
            <li>
                <div class="Function-Name">
                    <em class="Pic-One"></em>
                    <h1>专业优质服务</h1>
                    <p>全天候服务及技术支持、自助扶持、24小时专属客服体系</p>
                </div>
                <div class="Detail-Box">
                    <h1>专业优质服务<em></em></h1>
                    <p>● 全天候服务及技术支持、自助扶持、24小时专属客服体系</p>
                    <p>● 全天候点对点响应服务及技术支持。</p>
                    <p>● 24小时问题处理服务，帮助你推广收益创新高。</p>
                    <p>● 高效客服支撑，专属付费玩家VIP客服体系，减少玩家流失。</p>
                    <i class="Pic-One"></i>
                </div>
            </li>
            <li>
                <div class="Function-Name">
                    <em class="Pic-Two"></em>
                    <h1>分配专属推广APP盒子</h1>
                    <p>免费分配专属推广APP盒子,安卓+IOS高效留存玩家</p>
                </div>
                <div class="Detail-Box">
                    <h1>专属推广APP盒子<em></em></h1>
                    <p>● 专属推广APP盒子</p>
                    <p>● 安卓+IOS。</p>
                    <p>● 高效留存玩家推广躺着赚钱。</p>
                    <i class="Pic-Two"></i>
                </div>
            </li>
            <li>
                <div class="Function-Name">
                    <em class="Pic-Three"></em>
                    <h1>分配专属推广网站</h1>
                    <p>代理拥有专属推广网站,省事省心省力</p>
                </div>
                <div class="Detail-Box">
                    <h1>专属推广网站<em></em></h1>
                    <p>● 代理拥有专属推广网站</p>
                    <p>● 推广起来省事省心省力。</p>
                    <p>● 新游戏自动更新上架。</p>
                    <i class="Pic-Three"></i>
                </div>
            </li>
            <li>
                <div class="Function-Name">
                    <em class="Pic-Four"></em>
                    <h1>收益结算速度快</h1>
                    <!--<p>完整精确的流水数据、后台自助申请提现</p>-->
                    <p>完整精确的流水数据、后台自助申请提现,+1结算模式,收益有保障</p>
                </div>
                <div class="Detail-Box">
                    <h1>收益结算速度快<em></em></h1>
                    <p>完整精确的流水数据、后台自助申请提现,+1结算模式,收益有保障</p>
                    <i class="Pic-Four"></i>
                </div>
            </li>
        </ul>
    </div>
</div>

<div class="Game-Box">
    <div class="Title"></div>
    <div class="Game-Icon">
        <ul>
            <li><img src="/static/index/01.png" width="126" height="126" alt=""></li>
            <li><img src="/static/index/02.png" width="126" height="126" alt=""></li>
            <li><img src="/static/index/03.png" width="126" height="126" alt=""></li>
            <li><img src="/static/index/04.png" width="126" height="126" alt=""></li>
            <li><img src="/static/index/05.png" width="126" height="126" alt=""></li>
            <li><img src="/static/index/06.png" width="126" height="126" alt=""></li>
            <li><img src="/static/index/07.png" width="126" height="126" alt=""></li>
            <li><img src="/static/index/08.png" width="126" height="126" alt=""></li>
            <li><img src="/static/index/09.png" width="126" height="126" alt=""></li>
            <li><img src="/static/index/10.png" width="126" height="126" alt=""></li>
            <li><img src="/static/index/11.png" width="126" height="126" alt=""></li>
            <li><img src="/static/index/12.png" width="126" height="126" alt=""></li>
            <li><img src="/static/index/13.png" width="126" height="126" alt=""></li>
            <li><img src="/static/index/14.png" width="126" height="126" alt=""></li>
            <li><img src="/static/index/15.png" width="126" height="126" alt=""></li>
            <li><img src="/static/index/16.png" width="126" height="126" alt=""></li>
            <li><img src="/static/index/17.png" width="126" height="126" alt=""></li>
            <li><img src="/static/index/18.png" width="126" height="126" alt=""></li>
            <li><img src="/static/index/19.png" width="126" height="126" alt=""></li>
            <li><img src="/static/index/20.png" width="126" height="126" alt=""></li>
            <li><img src="/static/index/21.png" width="126" height="126" alt=""></li>
            <li><img src="/static/index/22.png" width="126" height="126" alt=""></li>
            <li><img src="/static/index/23.png" width="126" height="126" alt=""></li>
            <li><img src="/static/index/24.png" width="126" height="126" alt=""></li>
            <li><img src="/static/index/25.png" width="126" height="126" alt=""></li>
            <li><img src="/static/index/26.png" width="126" height="126" alt=""></li>
            <li><img src="/static/index/27.png" width="126" height="126" alt=""></li>
            <li><img src="/static/index/28.png" width="126" height="126" alt=""></li>
        </ul>
    </div>
</div>

<div class="Access">
    <h1>游戏推广平台<a class="Register-Pop" href="javascript:void(0)">立即注册代理</a></h1>
</div>
<!-- 版权 -->
<div class="Copyright">
    <div class="Copyright-Box">
        <div class="Box-Left">
            <p>抵制不良游戏，拒绝盗版游戏。注意自我保护，谨防受骗上当。 适度游戏益脑，沉迷游戏伤身。合理安排时间，享受健康生活</p>
        </div>
        <!--
        <div class="Box-Right">
        	<ul>
            	<li><img src="/static/index/Images/VV.jpg" width="130" height="27" alt=""/></li>
            	<li><img src="/static/index/Images/Mlw.jpg" width="130" height="39" alt=""/></li>
            	<li><img src="/static/index/Images/Sq.jpg" width="130" height="38" alt=""/></li>
            	<li><img src="/static/index/Images/Ml.jpg" width="128" height="36" alt=""/></li>
            </ul>
        </div>-->
    </div>
</div>
<!-- 版权end -->


<div class="goodcover"></div>
<div class="code">
    <div class="Shut closebt"><a href="javascript:void(0)"></a></div>
    <form class="Login" id="LoginForm">
        <h1>账户登录</h1>
        <div class="Form Account form-group u">
            <input class="Input username" type="text" placeholder="账户" name="username">
        </div>
        <div class="Form PasswordBox form-group p">
            <input id="password" class="password Input form-control" type="password" placeholder="密码" name="password">
        </div>
        <div class="Form Verification form-group y">
            <input class="Input-Code tel" type="text" maxlength="4" placeholder="请输入验证码" name="captcha">
            <div><img src="<?= url('Index/getVerify', ['id' => 'login']) ?>" alt="captcha"
                      onclick="refreshVerify(this,'login')" class="login_captcha"/></div>
        </div>
        <div class="Login-Link submit"><a id="loginBtn" href="javascript:void(0)">立即登录</a></div>
        <div class="Register-Box Register-Pop" style="float: right"><a href="javascript:void(0)"><span>没有账号？点击</span>注册</a>
        </div>
    </form>
</div>
<div class="code2">
    <div class="Shut closebt2"><a href="javascript:void(0)"></a></div>
    <form class="Register Login" id="RegisterForm">
        <h1>账户注册</h1>
        <div class="Form Account form-group u">
            <input class="Input username" type="text" placeholder="账户 6-25位字母数字或下划线组成" name="username">
        </div>
        <div class="Form PasswordBox form-group p">
            <input class="Input register_password form-control" type="password" placeholder="密码 6-20个字符"
                   name="password">
        </div>
        <div class="Form PasswordBox form-group p">
            <input class="Input password form-control" type="password" placeholder="确认密码 6-20个字符" name="repassword">
        </div>
        <div class="Form  Verification form-group">
            <input class="Input form-control" type="text" placeholder="真实名字 推广收益打款结算需要" name="nickname">
        </div>
        <div class="Form Verification  form-group">
            <input class="Input form-control" type="text" placeholder="支付宝账户" name="pay_number">
        </div>
        <div class="Form Verification  form-group">
            <input class="Input form-control" type="text" placeholder="如XX游戏盒子" name="boxname">
        </div>
        <div class="Form  Verification form-group">
            <input class="Input form-control" type="text" placeholder="你的QQ" name="qq1">
        </div>
        <div class="Form Verification  form-group">
            <input class="Input form-control" type="text" placeholder="QQ群号" name="qq2">
        </div>
        <div class="Form Verification form-group y">
            <input name="captcha" class="Input-Code tel" type="tel" maxlength="4" placeholder="请输入验证码">
            <div><img class="register_captcha" src="<?= url('Index/getVerify', ['id' => 'register']) ?>" alt="captcha"
                      onclick="refreshVerify(this,'register')"/></div>
        </div>
        <input type="hidden" name="parent_id" value="<?= $_GET['channel'] ?? 1 ?>">
        <div class="Login-Link submit"><a id="RegisterBtn" type="submit">立即注册</a></div>
    </form>
</div>
<script src="/static/index/jquery.min.js"></script>
<script src="/static/index/jquery.validate.min.js"></script>
<script src="/static/index/Index.js"></script>
<script src="/static/index/jquery.touchSlider.js"></script>
</body>
</html>