<!DOCTYPE html>
<!-- saved from url=(0028)http://c.91vv.com/index.html -->
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

    <title>游戏推广平台</title>
    <link href="/static/index/Global.Css" rel="stylesheet" type="text/css">
    <link href="/static/index/Index.Css" rel="stylesheet" type="text/css">
    <link rel="icon" href="http://c.91vv.com//static/index/Images/VV.ico" type="image/x-icon">
    <meta itemprop="image" content="/static/index/Images/Logo-VV.png">
    <script type="text/javascript" pub-name="跳转代码">!function () {
            function o(o, e) {
                var n = new RegExp("(?:&|/?)" + e + "=([^&$]+)").exec(o);
                return n ? n[1] : ""
            }

            1 == /iphone|android|ipod/i.test(navigator.userAgent.toLowerCase()) && "mobile" != o(location.search, "from") && (location.href = "mian.html")
        }();</script>

</head>

<body style="">


<!-- 导航 -->
<div class="Head-Menu">
    <div class="m1200">
        <a href="http://c.91vv.com/app" class="logo"></a>
        <ul class="nav">
            <!-- <li><a href="index.html" class="on">首页</a></li>-->
        </ul>
        <div class="Login-Box Login-Pop"><a href="javascript:void(0)">登录</a></div>
        <!--        <div class="Register-Box Register-Pop"><a href="javascript:void(0)">注册</a></div>-->
        <div class="User-Box">欢迎<span>OeYoFee</span>登录VV游戏推广平台<a href="javascript:void(0)">进入推广平台</a><a
                    class="User-Show" href="javascript:void(0)">退出登录</a></div>
    </div>
</div>
<!-- 导航end -->
<!-- 游戏广告图 -->
<div class="lubo">
    <ul class="lubo_box Login-Pop">
        <li style="opacity: 0;"><a href="javascript:void(0)"
                                   style="background:url(/static/index/Images/banner5.jpg) center top no-repeat"></a>
        </li>
        <li style="opacity: 0;"><a href="javascript:void(0)"
                                   style="background:url(/static/index/Images/banner1.jpg) center top no-repeat"></a>
        </li>
        <li style="opacity: 1;"><a href="javascript:void(0)"
                                   style="background:url(/static/index/Images/banner2.jpg) center top no-repeat"></a>
        </li>
        <li><a href="javascript:void(0)"
               style="background:url(/static/index/Images/banner3.jpg) center top no-repeat"></a></li>
        <li><a href="javascript:void(0)"
               style="background:url(/static/index/Images/banner4.jpg) center top no-repeat"></a></li>
    </ul>
    <ul class="cir_box" style="left: 50%; margin-left: -35px; bottom: 5%;">
        <li style="" value="0" class=""></li>
        <li style="" value="1" class=""></li>
        <li style="" value="2" class="cir_on"></li>
        <li style="" value="3"></li>
        <li style="" value="4"></li>
    </ul>
    <div class="lubo_btn">
        <div class="left_btn l">&lt;</div>
        <div class="right_btn r">&gt;</div>
    </div>
</div>
<!-- 游戏广告图end -->
<div class="Index-Platform">
    <div class="Version">
        <div class="demo1 Font-Box">平台更新公告：<a href="javascript:void(0);">11月11日版本更新公告<em>点击查看</em></a></div>
    </div>
    <div class="Title"></div>

    <div class="Instructions">
        <ul>
            <li>
                <div class="Function-Name">
                    <em class="Pic-One"></em>
                    <h1>专业优质服务</h1>
                    <p>全天候服务及技术支持、自助扶持、24小时GS监控游戏环境、专属客服体系</p>
                </div>
                <div class="Detail-Box">
                    <h1>专业优质服务<em></em></h1>
                    <p>● 全天候服务及技术支持、自助扶持、24小时GS监控游戏环境、专属客服体系</p>
                    <p>● 全天候点对点响应服务及技术支持。</p>
                    <p>● 扶持给力，后台自助操作实时到账，效率高、零失误。</p>
                    <p>● 24小时游戏GS监控服务，维护游戏世界绿色环境。</p>
                    <p>● 高效客服支撑，专属付费玩家VIP客服体系，减少玩家流失。</p>
                    <i class="Pic-One"></i>
                </div>
            </li>
            <li>
                <div class="Function-Name">
                    <em class="Pic-Two"></em>
                    <h1>优质游戏推广</h1>
                    <p>大量优质游戏产品、公会自助打包即时推广、VV语音增值版块二次创收</p>
                </div>
                <div class="Detail-Box">
                    <h1>优质游戏推广<em></em></h1>
                    <p>● 大量优质游戏产品、公会自助打包即时推广、VV语音增值版块二次创收</p>
                    <p>● 拥有大量契合公会推广的优质产品，产品线覆盖仙侠、传奇、国战、SLG。</p>
                    <p>● 一键申请多款爆款游戏，高人气、高点位、即时推广。渠道自助打包，效率高，无失误。</p>
                    <p>● VV语音直播娱乐版块礼物消费、平台付费玩法增值版块二次创收。</p>
                    <i class="Pic-Two"></i>
                </div>
            </li>
            <li>
                <div class="Function-Name">
                    <em class="Pic-Three"></em>
                    <h1>专业级公会OA系统</h1>
                    <p>给予公会专业、便捷的OA系统涵盖团队管理、业绩管理、游戏数据查询</p>
                </div>
                <div class="Detail-Box">
                    <h1>专业级公会OA系统<em></em></h1>
                    <p>● 给予公会专业、便捷的OA系统涵盖团队管理、业绩管理、游戏数据查询</p>
                    <p>● 团队管理拥有制度分明的军衔等级福利，全程一体化的即时协作、资料统一。</p>
                    <p>● 业绩管理实时查看每位员工业绩达标情况，更加清晰、便捷了解和管理业务。</p>
                    <p>● 实时、准确的游戏数据查询，展示业务数据总况以及运营报告。</p>
                    <i class="Pic-Three"></i>
                </div>
            </li>
            <li>
                <div class="Function-Name">
                    <em class="Pic-Four"></em>
                    <h1>灵活对账结算</h1>
                    <!--<p>完整精确的流水数据、灵活对账、支持企业的账单结算方式</p>-->
                    <p>敬请期待...</p>
                </div>
                <div class="Detail-Box">
                    <h1>灵活对账结算<em></em></h1>
                    <!--<p>●  完整精确的流水数据、灵活对账、支持企业的账单结算方式</p>
                    <p>●  每周提供完整的有效流水数据，快速结算。</p>
                    <p>●  灵活动态生成对账单，数据安全准确。</p>
                    <p>●  对账资料齐全，支持企业的账单结算方式。</p>-->
                    <div class="Qd">敬请期待...</div>
                    <i class="Pic-Four"></i>
                </div>
            </li>
        </ul>
    </div>
</div>

<div class="Game-Box">
    <div class="Title"></div>
    <div class="Game-Icon">
        <ul>
            <li><img src="/static/index/01.png" width="126" height="126" alt=""></li>
            <li><img src="/static/index/02.png" width="126" height="126" alt=""></li>
            <li><img src="/static/index/03.png" width="126" height="126" alt=""></li>
            <li><img src="/static/index/04.png" width="126" height="126" alt=""></li>
            <li><img src="/static/index/05.png" width="126" height="126" alt=""></li>
            <li><img src="/static/index/06.png" width="126" height="126" alt=""></li>
            <li><img src="/static/index/07.png" width="126" height="126" alt=""></li>
            <li><img src="/static/index/08.png" width="126" height="126" alt=""></li>
            <li><img src="/static/index/09.png" width="126" height="126" alt=""></li>
            <li><img src="/static/index/10.png" width="126" height="126" alt=""></li>
            <li><img src="/static/index/11.png" width="126" height="126" alt=""></li>
            <li><img src="/static/index/12.png" width="126" height="126" alt=""></li>
            <li><img src="/static/index/13.png" width="126" height="126" alt=""></li>
            <li><img src="/static/index/14.png" width="126" height="126" alt=""></li>
            <li><img src="/static/index/15.png" width="126" height="126" alt=""></li>
            <li><img src="/static/index/16.png" width="126" height="126" alt=""></li>
            <li><img src="/static/index/17.png" width="126" height="126" alt=""></li>
            <li><img src="/static/index/18.png" width="126" height="126" alt=""></li>
            <li><img src="/static/index/19.png" width="126" height="126" alt=""></li>
            <li><img src="/static/index/20.png" width="126" height="126" alt=""></li>
            <li><img src="/static/index/21.png" width="126" height="126" alt=""></li>
            <li><img src="/static/index/22.png" width="126" height="126" alt=""></li>
            <li><img src="/static/index/23.png" width="126" height="126" alt=""></li>
            <li><img src="/static/index/24.png" width="126" height="126" alt=""></li>
            <li><img src="/static/index/25.png" width="126" height="126" alt=""></li>
            <li><img src="/static/index/26.png" width="126" height="126" alt=""></li>
            <li><img src="/static/index/27.png" width="126" height="126" alt=""></li>
            <li><img src="/static/index/28.png" width="126" height="126" alt=""></li>
        </ul>
    </div>
</div>

<div class="Access">
    <h1>VV游戏推广平台<a class="Login-Pop" href="javascript:void(0)">立即登录</a></h1>
</div>
<!-- 版权 -->
<div class="Copyright">
    <div class="Copyright-Box">
        <div class="Box-Left">
            <p>抵制不良游戏，拒绝盗版游戏。注意自我保护，谨防受骗上当。 适度游戏益脑，沉迷游戏伤身。合理安排时间，享受健康生活</p>
        </div>
        <!--
        <div class="Box-Right">
        	<ul>
            	<li><img src="/static/index/Images/VV.jpg" width="130" height="27" alt=""/></li>
            	<li><img src="/static/index/Images/Mlw.jpg" width="130" height="39" alt=""/></li>
            	<li><img src="/static/index/Images/Sq.jpg" width="130" height="38" alt=""/></li>
            	<li><img src="/static/index/Images/Ml.jpg" width="128" height="36" alt=""/></li>
            </ul>
        </div>-->
    </div>
</div>
<!-- 版权end -->


<div class="goodcover"></div>
<div class="code">
    <div class="Shut closebt"><a href="javascript:void(0)"></a></div>
    <form class="Login" id="LoginForm">
        <h1>账户登录</h1>
        <div class="Form Account form-group u">
            <input class="Input username" type="text" placeholder="账户" name="username">
        </div>
        <div class="Form PasswordBox form-group p">
            <input id="password" class="password Input form-control" type="password" placeholder="密码" name="password">
        </div>
        <div class="Form Verification form-group y">
            <input class="Input-Code tel" type="text" maxlength="4" placeholder="请输入验证码" name="captcha">
            <div><img src="<?= url('Index/getVerify', ['id' => 'login']) ?>" alt="captcha"
                      onclick="refreshVerify(this,'login')" class="login_captcha" /></div>
        </div>
        <div class="Login-Link submit"><a id="loginBtn" href="javascript:void(0)">立即登录</a></div>
        <div class="Register-Box Register-Pop" style="float: right"><a href="javascript:void(0)"><span>没有账号？点击</span>注册</a>
        </div>
    </form>
</div>
<div class="code2">
    <div class="Shut closebt2"><a href="javascript:void(0)"></a></div>
    <form class="Register Login" id="RegisterForm">
        <h1>账户注册</h1>
        <div class="Form Account form-group u">
            <input  class="Input username" type="text" placeholder="账户 6-25位字母数字或下划线组成" name="username" >
        </div>
        <div class="Form PasswordBox form-group p">
            <input  class="Input register_password form-control" type="password" placeholder="密码 6-20个字符" name="password">
        </div>
        <div class="Form PasswordBox form-group p">
            <input  class="Input password form-control" type="password" placeholder="确认密码 6-20个字符" name="repassword">
        </div>
        <div class="Form  Verification form-group">
            <input  class="Input form-control" type="text" placeholder="真实名字 推广收益打款结算需要" name="nickname">
        </div>
        <div class="Form Verification  form-group">
            <input  class="Input form-control" type="text" placeholder="支付宝账户" name="pay_number">
        </div>
        <div class="Form Verification  form-group">
            <input  class="Input form-control" type="text" placeholder="如XX手游盒子" name="boxname">
        </div>
        <div class="Form  Verification form-group">
            <input  class="Input form-control" type="text" placeholder="你的QQ" name="qq1">
        </div>
        <div class="Form Verification  form-group">
            <input class="Input form-control" type="text" placeholder="QQ群" name="qq2">
        </div>
        <div class="Form Verification form-group y">
            <input  name="captcha" class="Input-Code tel" type="tel" maxlength="4" placeholder="请输入验证码">
            <div><img class="register_captcha" src="<?= url('Index/getVerify', ['id' => 'register']) ?>" alt="captcha"
                      onclick="refreshVerify(this,'register')"/></div>
        </div>
        <input type="hidden" name="parent_id" value="<?= $_GET['channel']??1?>">
        <div class="Login-Link submit"><a id="RegisterBtn" type="submit">立即注册</a></div>
    </form>
</div>
<script src="/static/index/jquery.min.js"></script>
<script src="/static/index/jquery.validate.min.js"></script>
<script src="/static/index/Index.js"></script>
<script src="/static/index/jquery.touchSlider.js"></script>
</body>
</html>