<!DOCTYPE html>
<!-- saved from url=(0042)http://yun.wuyousy.com/Down.html?g=1000334 -->
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <script src="/channel/hm.js"></script>
    <script type="text/javascript">if (window != top) top.location.href = window.location.href; </script>

    <meta id="viewport" name="viewport"
          content="width=device-width, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">
    <title>GM</title>
    <meta name="keywords"
          content="gm">
    <meta name="description" content="gm ">
    <link rel="stylesheet" type="text/css" href="/channel/swiper.min.css">
    <link rel="stylesheet" type="text/css" href="/channel/style.css">
    <script src="/channel/jquery-1.9.1.min.js"></script>
    <script src="/channel/swiper.min.js"></script>
    <script src="/public/scripts/jquery.qrcode.min.js"></script>
</head>
<body class="bg-e">
<div class="banner" id="first-banner">
    <img src="/channel/banner01.jpg">
</div>
<div class="leiji-download" style="background-color:#7c1ebc">
    <div class="download-l" style="font-size: 3rem;color: #ffffff;font-family: 楷体;background-color:#7c1ebc">
        <b>游戏盒子</b>
    </div>
</div>
<section class="z-products" style="padding-top: 0px; max-width: 640px;">
    <div class="jianjie-button">
        <a href="<?= $info['download_url'] ?>" id="and_url" onclick="IncDownCnt(100)"><img src="/channel/button02.png"></a>
        <a href="<?= $info['play_url'] ?>"><img src="/channel/button03.png"></a>
        <a href="<?= $info['download_url2'] ?>" id="ios_url" onclick="IncDownCnt(101)"><img src="/channel/button01.png"></a>
    </div>
    <div class="teshe">
        <div class="teshe-title">
            <img src="/channel/title02.png">
        </div>
        <div class="teshe-leir">
            <table style="width:100%;" cellpadding="2" cellspacing="0" border="1" bordercolor="#999999">
                <tbody>
                <tr>
                    <td>
                        <div style="text-align:left;">
                            福利：上线就赠送满级VIP+超多钻石；
                        </div>
                        <div style="text-align:left;">
                            版本：不用下载点击在线即玩，安卓+IOS+电脑；
                        </div>
                        <div style="text-align:left;">
                            特权：游戏内置GM特权,不用退出狂刷一切；
                        </div>
                        <div style="text-align:left;">
                            品质：SSS级产品品质,人气爆满；
                        </div>
                    </td>
                    <td>
                        <p style="text-align:center;">
                            扫描二维码手机访问页面：
                        </p>
                        <p style="text-align:center;" id="qrcode">
                        </p>
                    </td>
                </tr>
                </tbody>
            </table>

        </div>
    </div>
    <div class="game-xx-banner">
        <!-- Swiper -->
        <div class="swiper-container swiper-container-horizontal">
            <div class="swiper-wrapper">
                <div class="swiper-slide swiper-slide-active" style="margin-right: 10px;">
                    <img class="pic" data-src-wide="/data2/img01-1.jpg" src="/channel/img01-1.jpg">
                </div>
                <div class="swiper-slide swiper-slide-next" style="margin-right: 10px;">
                    <img class="pic" data-src-wide="/data2/img02-1.jpg" src="/channel/img02-1.jpg">
                </div>
                <div class="swiper-slide" style="margin-right: 10px;">
                    <img class="pic" data-src-wide="/data2/img03-1.jpg" src="/channel/img03-1.jpg">
                </div>
                <div class="swiper-slide" style="margin-right: 10px;">
                    <img class="pic" data-src-wide="/data2/img04-1.jpg" src="/channel/img04-1.jpg">
                </div>
                <div class="swiper-slide" style="margin-right: 10px;">
                    <img class="pic" data-src-wide="/data2/img05-1.jpg" src="/channel/img05-1.jpg">
                </div>
            </div>
            <!-- Add Pagination -->
            <div class="swiper-pagination swiper-pagination-clickable swiper-pagination-bullets">
                <span class="swiper-pagination-bullet swiper-pagination-bullet-active"></span><span
                        class="swiper-pagination-bullet"></span><span class="swiper-pagination-bullet"></span><span
                        class="swiper-pagination-bullet"></span></div>
        </div>

        <!--end Swiper -->
    </div>

    <link href="/channel/app.css" rel="stylesheet" type="text/css">
    <div id="weixin_an" style="display: none">

        <div class="click_opacity"></div>
        <div class="to_btn">
            <span class="span1"><img src="/channel/click_btn.png"></span>
            <span class="span2"><em>1</em> 点击右上角<img src="/channel/menu_android.png">打开菜单</span>
            <span class="span2 android_open"><em>2</em> 选择<img src="/channel/android.png"></span>
        </div>
    </div>

    <!-- Initialize Swiper -->
    <script>          var mySwiper = new Swiper('.swiper-container', {
            pagination: '.swiper-pagination',
            slidesPerView: 'auto',
            paginationClickable: true,
            spaceBetween: 10,

        })
    </script>
    <!-- end Initialize Swiper -->
    <!--点击放大-->
    <div class="carrousel">
        <div class="wrapper02">
            <img src="http://yun.wuyousy.com/Down.html?g=1000334">
        </div>
    </div>
    <script>
        $(function () {
            var carrousel = $(".carrousel");

            $(".swiper-slide").click(function (e) {
                var src = $(this).find(".pic").attr("data-src-wide");
                carrousel.find("img").attr("src", src);
                carrousel.fadeIn(200);

                $('body').bind("touchmove", function (e) {
                    e.preventDefault();
                });

            });

            carrousel.click(function (e) {
                carrousel.find("img").attr("src", '');
                carrousel.fadeOut(200);
                $("body").unbind("touchmove");
            });

        })
    </script>
    <!--end 点击放大-->
    <div class="banner">
        <img src="/channel/img05.png">
    </div>
    <div class="touf-btn">
<!--        商务合作:gmhezuo@qq.com-->
    </div>
</section>
<script>
    window.onload = function () {
        var bannerH = $('.z-products').offset().top;  //当前位置距TOP距离
        var topH = bannerH
        var buttonH = $(".jianjie-button").outerHeight();  //按钮所站的位置高度
        var topH2 = buttonH

        $(window).scroll(function () {
            var height = ($(document).scrollTop());
            if (height > topH) {
                $(".z-products").addClass("div-fixed").css({"paddingTop": topH2});
            } else if (height < topH) {
                $(".z-products").removeClass("div-fixed ").css({"paddingTop": 0});
            } else {
                return;
            }
        });

    }
</script>
<div class="tishi" style="display:none;">
    <img src="/channel/mengb-weixin.png">
    <!--安卓mengb-an.png-->
</div>

<script>
    function IncDownCnt(appid) {
        var ua = navigator.userAgent.toLowerCase();
        if (/iphone|ipad|ipod/.test(ua)) {
            if (appid == 100) {
                $('#and_url').attr('href', '#');
                alert('苹果手机不能下载安卓包哦！');
                return;
            }
        } else if (/android/.test(ua)) {
            if (appid == 101) {
                $('#ios_url').attr('href', '#');
                alert('安卓手机不能下载苹果包哦！');
                return;
            }
            if (ua.match(/MicroMessenger/i) == "micromessenger") {
                $('#weixin_an').show();
            }
        }


    }
    $('#qrcode').qrcode({
        text:"<?=$info['play_url']?>",
        width: 160, //宽度
        height:160, //高度
        background: "#ffffff",
        correctLevel: 0,//纠错等级
    });
</script>

</body>
</html>